export const AUTH_LOGIN_PAYLOAD_MAX_CHARS = 128 * 1024;
export const AUTH_LOGIN_VERSION = 1 as const;

const AUTH_LOGIN_PAYLOAD_KEYS = [
  "challenge_id",
  "challenge",
  "node_identifier",
  "expires_at",
  "public_key",
  "signature",
  "version",
] as const;

const AUTH_LOGIN_PAYLOAD_KEY_SET = new Set<string>(AUTH_LOGIN_PAYLOAD_KEYS);
const NODE_IDENTIFIER_PATTERN = /^[0-9a-f]{64}$/;
const MAX_BYTE_ARRAY_LENGTH = 16 * 1024;

type AuthLoginPayloadKey = (typeof AUTH_LOGIN_PAYLOAD_KEYS)[number];

export type AuthLoginPayload = {
  [Key in AuthLoginPayloadKey]: Key extends "expires_at" | "version"
    ? number
    : Key extends "public_key" | "signature"
      ? number[]
      : string;
} & {
  version: typeof AUTH_LOGIN_VERSION;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function readNonEmptyString(value: unknown, message: string): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new Error(message);
  }
  return value;
}

function readByteArray(value: unknown, fieldName: string): number[] {
  if (
    !Array.isArray(value) ||
    value.length === 0 ||
    value.length > MAX_BYTE_ARRAY_LENGTH ||
    !value.every(
      (byte) =>
        typeof byte === "number" &&
        Number.isInteger(byte) &&
        byte >= 0 &&
        byte <= 255,
    )
  ) {
    throw new Error(`${fieldName} must be a non-empty byte array.`);
  }
  return [...value] as number[];
}

function skipJsonString(raw: string, start: number): number {
  let index = start + 1;
  let escaped = false;

  while (index < raw.length) {
    const character = raw[index];
    index += 1;

    if (escaped) {
      escaped = false;
    } else if (character === "\\") {
      escaped = true;
    } else if (character === '"') {
      return index;
    }
  }

  return raw.length;
}

function skipJsonValue(raw: string, start: number): number {
  const firstCharacter = raw[start];
  if (firstCharacter === '"') return skipJsonString(raw, start);

  if (firstCharacter === "{" || firstCharacter === "[") {
    const closingCharacters = firstCharacter === "{" ? "}" : "]";
    const stack = [closingCharacters];
    let index = start + 1;

    while (index < raw.length && stack.length > 0) {
      const character = raw[index];
      if (character === '"') {
        index = skipJsonString(raw, index);
        continue;
      }
      if (character === "{" || character === "[") {
        stack.push(character === "{" ? "}" : "]");
      } else if (character === stack[stack.length - 1]) {
        stack.pop();
      }
      index += 1;
    }

    return index;
  }

  let index = start;
  while (index < raw.length && raw[index] !== "," && raw[index] !== "}") {
    index += 1;
  }
  return index;
}

function hasDuplicateTopLevelKeys(raw: string): boolean {
  const isWhitespace = /\s/;
  let index = 0;
  while (isWhitespace.test(raw[index] ?? "")) index += 1;
  if (raw[index] !== "{") return false;
  index += 1;

  const keys = new Set<string>();
  while (index < raw.length) {
    while (isWhitespace.test(raw[index] ?? "")) index += 1;
    if (raw[index] === "}") return false;
    if (raw[index] !== '"') return false;

    const keyStart = index;
    index = skipJsonString(raw, index);
    const key = JSON.parse(raw.slice(keyStart, index)) as unknown;
    if (typeof key !== "string") return false;
    if (keys.has(key)) return true;
    keys.add(key);

    while (isWhitespace.test(raw[index] ?? "")) index += 1;
    if (raw[index] !== ":") return false;
    index += 1;
    while (isWhitespace.test(raw[index] ?? "")) index += 1;
    index = skipJsonValue(raw, index);

    while (isWhitespace.test(raw[index] ?? "")) index += 1;
    if (raw[index] === "}") return false;
    if (raw[index] !== ",") return false;
    index += 1;
  }

  return false;
}

/**
 * Parse only the public, direct POST /api/auth/login payload emitted by the CLI.
 * This function intentionally has no network, storage, logging, or URL side effects.
 */
export function parseAuthLoginPayload(raw: string): AuthLoginPayload {
  if (raw.length > AUTH_LOGIN_PAYLOAD_MAX_CHARS) {
    throw new Error("Signed payload is too large. Paste the public CLI JSON only.");
  }
  if (raw.trim().length === 0) {
    throw new Error("Paste the JSON payload generated by ultranet-auth.");
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    throw new Error("Signed payload is not valid JSON.");
  }

  if (!isRecord(parsed)) {
    throw new Error("Signed payload must be a JSON object.");
  }
  if (hasDuplicateTopLevelKeys(raw)) {
    throw new Error("Signed payload contains duplicate fields.");
  }

  const keys = Object.keys(parsed);
  if (
    keys.length !== AUTH_LOGIN_PAYLOAD_KEYS.length ||
    keys.some((key) => !AUTH_LOGIN_PAYLOAD_KEY_SET.has(key))
  ) {
    throw new Error("Signed payload contains unsupported or missing fields.");
  }

  const challengeId = readNonEmptyString(
    parsed.challenge_id,
    "Signed payload is missing a challenge identifier.",
  );
  const challenge = readNonEmptyString(
    parsed.challenge,
    "Signed payload is missing a challenge.",
  );
  const nodeIdentifier = readNonEmptyString(
    parsed.node_identifier,
    "Signed payload is missing a node identifier.",
  );
  if (!NODE_IDENTIFIER_PATTERN.test(nodeIdentifier)) {
    throw new Error("Node identifier must be 64 lowercase hexadecimal characters.");
  }

  if (
    typeof parsed.expires_at !== "number" ||
    !Number.isSafeInteger(parsed.expires_at) ||
    parsed.expires_at <= 0
  ) {
    throw new Error("Signed payload has an invalid expiration time.");
  }
  if (parsed.expires_at <= Math.floor(Date.now() / 1000)) {
    throw new Error("Signed payload has expired. Generate a fresh CLI payload.");
  }
  if (parsed.version !== AUTH_LOGIN_VERSION) {
    throw new Error("Signed payload uses an unsupported authentication version.");
  }

  return {
    challenge_id: challengeId,
    challenge,
    node_identifier: nodeIdentifier,
    expires_at: parsed.expires_at,
    public_key: readByteArray(parsed.public_key, "public_key"),
    signature: readByteArray(parsed.signature, "signature"),
    version: AUTH_LOGIN_VERSION,
  };
}
