import { describe, expect, it } from "vitest";
import {
  AUTH_LOGIN_PAYLOAD_MAX_CHARS,
  parseAuthLoginPayload,
} from "./auth-payload";

const FUTURE_EXPIRATION = () => Math.floor(Date.now() / 1000) + 60 * 60;

function createValidPayload() {
  return {
    challenge_id: "challenge-id",
    challenge: "challenge-value",
    node_identifier: "a".repeat(64),
    expires_at: FUTURE_EXPIRATION(),
    public_key: [1, 2, 3],
    signature: [4, 5, 6],
    version: 1,
  };
}

function asJson(payload: Record<string, unknown>): string {
  return JSON.stringify(payload);
}

function expectRejected(raw: string, message: string) {
  expect(() => parseAuthLoginPayload(raw)).toThrow(message);
}

describe("parseAuthLoginPayload", () => {
  it("accepts a valid public CLI payload and returns exactly its seven fields", () => {
    const payload = parseAuthLoginPayload(asJson(createValidPayload()));

    expect(Object.keys(payload).sort()).toEqual([
      "challenge",
      "challenge_id",
      "expires_at",
      "node_identifier",
      "public_key",
      "signature",
      "version",
    ]);
    expect(payload).toMatchObject(createValidPayload());
  });

  it("returns independent byte arrays for the public key and signature", () => {
    const payload = parseAuthLoginPayload(asJson(createValidPayload()));
    payload.public_key.push(7);

    expect(payload.public_key).toEqual([1, 2, 3, 7]);
    expect(payload.signature).toEqual([4, 5, 6]);
  });

  it.each([
    ["", "Paste the JSON payload generated by ultranet-auth."],
    ["   ", "Paste the JSON payload generated by ultranet-auth."],
    ["{", "Signed payload is not valid JSON."],
    ["null", "Signed payload must be a JSON object."],
    ["[]", "Signed payload must be a JSON object."],
    ["42", "Signed payload must be a JSON object."],
    ["\"payload\"", "Signed payload must be a JSON object."],
  ])("rejects %s input", (raw, message) => {
    expectRejected(raw, message);
  });

  it.each(["secret_key", "private_key", "sovereign_keys", "owners"])(
    "rejects private or sovereign field %s",
    (field) => {
      expectRejected(
        asJson({ ...createValidPayload(), [field]: [9, 9, 9] }),
        "Signed payload contains unsupported or missing fields.",
      );
    },
  );

  it.each([
    "challenge_id",
    "challenge",
    "node_identifier",
    "expires_at",
    "public_key",
    "signature",
    "version",
  ])("rejects a payload missing %s", (field) => {
    const payload = { ...createValidPayload() } as Record<string, unknown>;
    delete payload[field];

    expectRejected(
      asJson(payload),
      "Signed payload contains unsupported or missing fields.",
    );
  });

  it("rejects duplicate top-level fields instead of trusting JSON.parse last-write behavior", () => {
    const payload = createValidPayload();
    const raw = `${JSON.stringify(payload).slice(0, -1)},\"secret_key\":[9]}\n`;

    expectRejected(raw, "Signed payload contains unsupported or missing fields.");

    const duplicateChallenge = `${JSON.stringify(payload).slice(0, -1)},\"challenge\":\"replacement\"}`;
    expectRejected(duplicateChallenge, "Signed payload contains duplicate fields.");
  });

  it.each([
    ["challenge_id", "", "Signed payload is missing a challenge identifier."],
    ["challenge", "", "Signed payload is missing a challenge."],
    ["node_identifier", "", "Signed payload is missing a node identifier."],
    ["challenge_id", 123, "Signed payload is missing a challenge identifier."],
    ["challenge", null, "Signed payload is missing a challenge."],
    ["node_identifier", null, "Signed payload is missing a node identifier."],
  ] as const)("rejects invalid %s", (field, value, message) => {
    expectRejected(asJson({ ...createValidPayload(), [field]: value }), message);
  });

  it.each([
    "A".repeat(64),
    "a".repeat(63),
    "a".repeat(65),
    `${"a".repeat(63)}g`,
    "0x" + "a".repeat(62),
  ])("rejects invalid node identifier %s", (nodeIdentifier) => {
    expectRejected(
      asJson({ ...createValidPayload(), node_identifier: nodeIdentifier }),
      "Node identifier must be 64 lowercase hexadecimal characters.",
    );
  });

  it.each([
    ["expires_at", 0],
    ["expires_at", -1],
    ["expires_at", Math.floor(Date.now() / 1000) - 1],
    ["expires_at", 1.5],
    ["expires_at", Number.MAX_SAFE_INTEGER + 1],
    ["expires_at", "future"],
    ["expires_at", null],
  ] as const)("rejects invalid expiration value %s", (field, value) => {
    const message =
      typeof value === "number" &&
      Number.isSafeInteger(value) &&
      value > 0 &&
      value <= Math.floor(Date.now() / 1000)
        ? "Signed payload has expired. Generate a fresh CLI payload."
        : "Signed payload has an invalid expiration time.";

    expectRejected(asJson({ ...createValidPayload(), [field]: value }), message);
  });

  it("rejects an expiration exactly at the current second", () => {
    expectRejected(
      asJson({
        ...createValidPayload(),
        expires_at: Math.floor(Date.now() / 1000),
      }),
      "Signed payload has expired. Generate a fresh CLI payload.",
    );
  });

  it.each([0, 2, "1", null, true])("rejects unsupported version %s", (version) => {
    expectRejected(
      asJson({ ...createValidPayload(), version }),
      "Signed payload uses an unsupported authentication version.",
    );
  });

  it.each([
    [],
    "hex",
    [1.5],
    [-1],
    [256],
    [null],
    ["1"],
  ])("rejects invalid public_key byte arrays", (public_key) => {
    expectRejected(
      asJson({ ...createValidPayload(), public_key }),
      "public_key must be a non-empty byte array.",
    );
  });

  it.each([
    [],
    "hex",
    [1.5],
    [-1],
    [256],
    [null],
    ["1"],
  ])("rejects invalid signature byte arrays", (signature) => {
    expectRejected(
      asJson({ ...createValidPayload(), signature }),
      "signature must be a non-empty byte array.",
    );
  });

  it("rejects byte arrays above the parser limit", () => {
    const oversized = Array.from({ length: 16 * 1024 + 1 }, () => 0);

    expectRejected(
      asJson({ ...createValidPayload(), public_key: oversized }),
      "public_key must be a non-empty byte array.",
    );
  });

  it("accepts byte arrays at the parser limit", () => {
    const maximum = Array.from({ length: 16 * 1024 }, () => 0);

    expect(parseAuthLoginPayload(asJson({ ...createValidPayload(), public_key: maximum })))
      .toMatchObject({ public_key: maximum });
  });

  it("accepts a payload whose serialized size is exactly the configured character limit", () => {
    const base = createValidPayload();
    const emptyChallengeLength = asJson({ ...base, challenge: "" }).length;
    const exactPayload = {
      ...base,
      challenge: "x".repeat(AUTH_LOGIN_PAYLOAD_MAX_CHARS - emptyChallengeLength),
    };
    const raw = asJson(exactPayload);

    expect(raw).toHaveLength(AUTH_LOGIN_PAYLOAD_MAX_CHARS);
    expect(parseAuthLoginPayload(raw).challenge).toHaveLength(
      AUTH_LOGIN_PAYLOAD_MAX_CHARS - emptyChallengeLength,
    );
  });

  it("rejects a payload one character over the configured character limit", () => {
    const base = createValidPayload();
    const emptyChallengeLength = asJson({ ...base, challenge: "" }).length;
    const oversizedPayload = {
      ...base,
      challenge: "x".repeat(
        AUTH_LOGIN_PAYLOAD_MAX_CHARS - emptyChallengeLength + 1,
      ),
    };

    expectRejected(
      asJson(oversizedPayload),
      "Signed payload is too large. Paste the public CLI JSON only.",
    );
  });
});
